package me.lyft.android.application.constants;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import me.lyft.android.infrastructure.lyft.constants.BooleanConstant;
import me.lyft.android.infrastructure.lyft.constants.Constant;
import me.lyft.android.infrastructure.lyft.constants.DoubleConstant;
import me.lyft.android.infrastructure.lyft.constants.HashMapConstant;
import me.lyft.android.infrastructure.lyft.constants.ListConstant;
import me.lyft.android.infrastructure.lyft.constants.LongConstant;
import me.lyft.android.infrastructure.lyft.constants.StringConstant;

public class Constants
{
  public static Constant<String> API_BASE_URL = new StringConstant("apiBaseUrl", null);
  public static Constant<Long> AUTO_NAVIGATE_DISTANCE_THRESHOLD;
  public static Constant<Long> AUTO_RESTORE_DISTANCE_THRESHOLD;
  public static Constant<String> CANCEL_DETAIL_TEXT_CHARGE;
  public static Constant<String> CANCEL_SUBTITLE_MULTIPLE_OPTIONS;
  public static Constant<String> CANCEL_SUBTITLE_TEXT_CHARGE;
  public static Constant<String> CANCEL_SUBTITLE_TEXT_UNASSIGNED;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_COMPLETE_BODY;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_COMPLETE_TITLE;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_LOCATION_SERVICES_BODY;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_LOCATION_SERVICES_TITLE;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_PAGE1_BODY;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_PAGE1_TITLE;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_PAGE2_BODY;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_PAGE2_TITLE;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_PROFILE_PHOTO_BODY;
  public static Constant<String> CARPOOL_DRIVER_ONBOARDING_PROFILE_PHOTO_TITLE;
  public static Constant<String> CARPOOL_INVITE_REFERRAL_BASE_URL;
  public static Constant<String> CARPOOL_INVITE_TEXT;
  public static Constant<String> CARPOOL_ROUTE_FALLBACK_DIALOG_TITLE;
  public static Constant<String> CARPOOL_ROUTE_UNLOCK_BODY;
  public static Constant<String> CARPOOL_ROUTE_UNLOCK_TITLE;
  public static Constant<String> CC_DIALOG_SUBTITLE;
  public static Constant<String> CC_DIALOG_TITLE;
  public static Constant<String> CLASSIC_ROUTE_LINE_TYPE = new StringConstant("classicRouteLineType", "default");
  public static Constant<String> CLIPBOARD_INVITE_TEXT;
  public static Constant<String> CLIPBOARD_REFERRAL_BASE_URL;
  public static Constant<String> CLIPBOARD_REFERRAL_BASE_URL_PARALLAX;
  public static Constant<String> CONFIRM_DEFAULTED_PICKUP_DIALOG_TITLE_TEXT;
  public static Constant<String> COURIER_DIALOG_HEADER_MESSAGE;
  public static Constant<String> COURIER_DIALOG_HEADER_TITLE;
  public static Constant<String> COURIER_DIALOG_INFO_MESSAGE_ONE;
  public static Constant<String> COURIER_DIALOG_INFO_MESSAGE_TWO;
  public static Constant<String> COURIER_DIALOG_INFO_TITLE_ONE;
  public static Constant<String> COURIER_DIALOG_INFO_TITLE_TWO;
  public static Constant<String> COURIER_NO_SHOW_PENALTY_MESSAGE;
  public static Constant<Long> COURIER_PICKUP_COUNTDOWN_TIMEOUT_DRIVER;
  public static Constant<String> Carpool_ROUTE_FALLBACK_DIALOG_BODY;
  public static Constant<Double> DEFAULT_LOCATION_ACCURACY_THRESHOLD_METERS;
  public static Constant<String> DESTINY_DIALOG_HEADER_LABEL;
  public static Constant<String> DESTINY_DIALOG_HEADER_TEXT;
  public static Constant<String> DESTINY_DIALOG_SECTION_ONE_LABEL;
  public static Constant<String> DESTINY_DIALOG_SECTION_ONE_TEXT;
  public static Constant<String> DESTINY_DIALOG_SECTION_TWO_LABEL;
  public static Constant<String> DESTINY_DIALOG_SECTION_TWO_TEXT;
  public static Constant<String> DESTINY_ENDED_MODAL_TEXT;
  public static Constant<String> DESTINY_MATCHING_LABEL_TEXT;
  public static Constant<String> DESTINY_STARTED_MODAL_TEXT;
  public static Constant<String> DRIVER_PAY_STARTED_MESSAGE;
  public static Constant<String> DRIVER_STATS_DISCLAIMER;
  public static Constant<String> EMAIL_INVITE_TEXT;
  public static Constant<String> EMAIL_REFERRAL_BASE_URL;
  public static Constant<String> END_RIDE_CONFIRMATION_CANCEL_BUTTON;
  public static Constant<String> END_RIDE_CONFIRMATION_PASSENGER_NOT_PICKED_UP_BUTTON;
  public static Constant<String> END_RIDE_CONFIRMATION_PASSENGER_PICKED_UP_BUTTON;
  public static Constant<String> END_RIDE_CONFIRMATION_TITLE;
  public static Constant<String> EXPRESS_PAY_ACCOUNT_INCOMPLETE_LINK;
  public static Constant<String> EXPRESS_PAY_DEBIT_CARD_INFO_LINK;
  public static Constant<String> EXPRESS_PAY_INELIGIBLE_LINK;
  public static Constant<String> EXPRESS_PAY_INSUFFICIENT_EARNINGS_LINK;
  public static Constant<String> EXPRESS_PAY_PROMO_POP_UP_BUTTON_TEXT;
  public static Constant<String> EXPRESS_PAY_PROMO_POP_UP_TEXT;
  public static Constant<String> FACEBOOK_INVITE_TEXT;
  public static Constant<String> FACEBOOK_REFERRAL_BASE_URL;
  public static Constant<String> HANGOUTS_REFERRAL_BASE_URL;
  public static Constant<String> HANGOUT_INVITE_TEXT;
  public static Constant<String> HEATMAP_TILES_URL;
  public static Constant<String> INSURANCE_HELP_CENTER_URL;
  public static Constant<String> INVITE_MENU_TEXT;
  public static Constant<Double> LEANPLUM_POLLING_INTERVAL;
  public static Constant<Double> NETWORK_ANALYTICS_SAMPLING_RATE;
  public static Constant<String> ORGANIZATION_JOIN_DESCRIPTION;
  public static Constant<String> ORGANIZATION_JOIN_HEADER;
  public static Constant<String> PARTY_SIZE_CONFIRMATION_MESSAGE;
  public static Constant<String> PARTY_SIZE_CONFIRMATION_TITLE;
  public static Constant<Long> PG_SOCIAL_PROMPT_FREQUENCY;
  public static Constant<Long> PG_SOCIAL_PROMPT_TOTAL_TIMES;
  public static Constant<HashMap> PROMOTE_GIFTBOX_HINT;
  public static Constant<HashMap> PROMOTE_SPLIT_PAY_HINT;
  public static Constant<String> REFERRAL_HEADER_TEXT_FORMAT;
  public static Constant<HashMap> RIDE_TYPE_HINT;
  public static Constant<Long> ROUTE_DEVIATE_MAX;
  public static Constant<Long> ROUTE_DEVIATE_THRESHOLD;
  public static Constant<Long> ROUTE_DIRECTIONS_REFRESH_INTERVAL;
  public static Constant<Long> SEARCH_FALLBACK_THRESHOLD;
  public static Constant<String> SIGNUP_PROMO_BANNER;
  public static Constant<String> SIGNUP_TERMS_URL = new StringConstant("signupTermsUrl", "http://api.lyft.com.s3.amazonaws.com/static/terms.html");
  public static Constant<String> SMS_INVITE_TEXT;
  public static Constant<String> SMS_REFERRAL_BASE_URL;
  public static Constant<String> SPLIT_PAYMENT_FEE_TEXT;
  public static Constant<String> TWITTER_INVITE_TEXT;
  public static Constant<String> TWITTER_REFERRAL_BASE_URL;
  public static Constant<String> UNKNOWN_MEDIUM_INVITE_TEXT;
  public static Constant<String> UNKNOWN_REFERRAL_BASE_URL;
  public static Constant<Boolean> WARM_WELCOME_PROFILE_VISIBLE;
  public static Constant<Boolean> WAZE_SDK_ENABLED;
  public static Constant<List<String>> WHITELISTED_URLS;
  
  static
  {
    NETWORK_ANALYTICS_SAMPLING_RATE = new DoubleConstant("networkAnalyticsSamplingRate", Double.valueOf(0.0D));
    REFERRAL_HEADER_TEXT_FORMAT = new StringConstant("pgReferralHeaderTextFormat", null);
    INSURANCE_HELP_CENTER_URL = new StringConstant("insuranceHelpCenterUrl", "http://lft.to/COI");
    HEATMAP_TILES_URL = new StringConstant("heatmapTilesUrl", "");
    COURIER_PICKUP_COUNTDOWN_TIMEOUT_DRIVER = new LongConstant("courierPickupCountdownTimeDriver", Long.valueOf(70L));
    WHITELISTED_URLS = new ListConstant("whitelistedUrls", Collections.emptyList());
    CANCEL_SUBTITLE_TEXT_UNASSIGNED = new StringConstant("cancelSubtitleTextUnassigned", null);
    CANCEL_SUBTITLE_TEXT_CHARGE = new StringConstant("cancelSubtitleTextCharge", null);
    CANCEL_DETAIL_TEXT_CHARGE = new StringConstant("cancelDetailTextCharge", null);
    AUTO_NAVIGATE_DISTANCE_THRESHOLD = new LongConstant("autoNavigateDistanceThreshold", Long.valueOf(400L));
    AUTO_RESTORE_DISTANCE_THRESHOLD = new LongConstant("autoRestoreDistanceThreshold", Long.valueOf(240L));
    SMS_INVITE_TEXT = new StringConstant("inviteTextSms", null);
    TWITTER_INVITE_TEXT = new StringConstant("inviteTextTwitter", null);
    FACEBOOK_INVITE_TEXT = new StringConstant("inviteTextFacebook", null);
    CLIPBOARD_INVITE_TEXT = new StringConstant("inviteTextClipboard", null);
    HANGOUT_INVITE_TEXT = new StringConstant("inviteTextHangout", null);
    EMAIL_INVITE_TEXT = new StringConstant("inviteTextEmail", null);
    UNKNOWN_MEDIUM_INVITE_TEXT = new StringConstant("inviteTextUnknownMedium", null);
    DESTINY_DIALOG_HEADER_LABEL = new StringConstant("driverDestinationCardHeaderLabel", null);
    DESTINY_DIALOG_HEADER_TEXT = new StringConstant("driverDestinationCardHeaderText", null);
    DESTINY_DIALOG_SECTION_ONE_LABEL = new StringConstant("driverDestinationCardSection1Label", null);
    DESTINY_DIALOG_SECTION_ONE_TEXT = new StringConstant("driverDestinationCardSection1Text", null);
    DESTINY_DIALOG_SECTION_TWO_LABEL = new StringConstant("driverDestinationCardSection2Label", null);
    DESTINY_DIALOG_SECTION_TWO_TEXT = new StringConstant("driverDestinationCardSection2Text", null);
    DESTINY_MATCHING_LABEL_TEXT = new StringConstant("driverDestinationMatchingLabel", null);
    DESTINY_STARTED_MODAL_TEXT = new StringConstant("driverDestinationStartedModalText", null);
    DESTINY_ENDED_MODAL_TEXT = new StringConstant("driverDestinationEndedModalText", null);
    ORGANIZATION_JOIN_HEADER = new StringConstant("organizationJoinHeader", null);
    ORGANIZATION_JOIN_DESCRIPTION = new StringConstant("organizationJoinDescription", null);
    COURIER_NO_SHOW_PENALTY_MESSAGE = new StringConstant("courierPenaltyAmount", null);
    COURIER_DIALOG_HEADER_TITLE = new StringConstant("courierDialogHeaderTitle", null);
    COURIER_DIALOG_HEADER_MESSAGE = new StringConstant("courierDialogHeaderMessage", null);
    COURIER_DIALOG_INFO_TITLE_ONE = new StringConstant("courierDialogInfoTitle1", null);
    COURIER_DIALOG_INFO_MESSAGE_ONE = new StringConstant("courierDialogInfoMessage1", null);
    COURIER_DIALOG_INFO_TITLE_TWO = new StringConstant("courierDialogInfoTitle2", null);
    COURIER_DIALOG_INFO_MESSAGE_TWO = new StringConstant("courierDialogInfoMessage2", null);
    PARTY_SIZE_CONFIRMATION_TITLE = new StringConstant("partySizeConfirmationTitle", null);
    PARTY_SIZE_CONFIRMATION_MESSAGE = new StringConstant("partySizeConfirmationMessage", null);
    CANCEL_SUBTITLE_MULTIPLE_OPTIONS = new StringConstant("cancelSubtitleMultipleOptions", null);
    END_RIDE_CONFIRMATION_TITLE = new StringConstant("endRideConfirmationTitle", null);
    END_RIDE_CONFIRMATION_PASSENGER_PICKED_UP_BUTTON = new StringConstant("endRideConfirmationPassengerPickedUpButton", null);
    END_RIDE_CONFIRMATION_PASSENGER_NOT_PICKED_UP_BUTTON = new StringConstant("endRideConfirmationPassengerNotPickedUpButton", null);
    END_RIDE_CONFIRMATION_CANCEL_BUTTON = new StringConstant("endRideConfirmationCancelButton", null);
    ROUTE_DIRECTIONS_REFRESH_INTERVAL = new LongConstant("routeDirectionsRefreshInterval", Long.valueOf(15L));
    SIGNUP_PROMO_BANNER = new StringConstant("signupPromoBanner", null);
    DRIVER_STATS_DISCLAIMER = new StringConstant("driverStatsDisclaimer", null);
    SEARCH_FALLBACK_THRESHOLD = new LongConstant("searchFallbackThreshold", Long.valueOf(0L));
    SPLIT_PAYMENT_FEE_TEXT = new StringConstant("splitPaymentsFeeText", null);
    EXPRESS_PAY_INSUFFICIENT_EARNINGS_LINK = new StringConstant("expressPayInsufficientEarningsLink", null);
    EXPRESS_PAY_INELIGIBLE_LINK = new StringConstant("expressPayIneligibleLink", null);
    EXPRESS_PAY_ACCOUNT_INCOMPLETE_LINK = new StringConstant("expressPayAccountIncompleteLink", null);
    EXPRESS_PAY_PROMO_POP_UP_TEXT = new StringConstant("expressPayPromoPopUpText", null);
    EXPRESS_PAY_PROMO_POP_UP_BUTTON_TEXT = new StringConstant("expressPayPromoPopUpButtonText", null);
    EXPRESS_PAY_DEBIT_CARD_INFO_LINK = new StringConstant("expressPayDebitCardInfoLink", null);
    CONFIRM_DEFAULTED_PICKUP_DIALOG_TITLE_TEXT = new StringConstant("confirmDefaultedPickupDialogTitleText", null);
    DEFAULT_LOCATION_ACCURACY_THRESHOLD_METERS = new DoubleConstant("defaultLocationAccuracyThresholdInMeters", Double.valueOf(100.0D));
    LEANPLUM_POLLING_INTERVAL = new DoubleConstant("leanplumPollingInterval", Double.valueOf(300.0D));
    WAZE_SDK_ENABLED = new BooleanConstant("wazeSDKEnabled", Boolean.valueOf(true));
    CARPOOL_ROUTE_UNLOCK_TITLE = new StringConstant("chauffeurRouteUnlockTitle", null);
    CARPOOL_ROUTE_UNLOCK_BODY = new StringConstant("chauffeurRouteUnlockBody", null);
    CARPOOL_ROUTE_FALLBACK_DIALOG_TITLE = new StringConstant("chauffeurRouteFallbackDialogTitle", null);
    Carpool_ROUTE_FALLBACK_DIALOG_BODY = new StringConstant("chauffeurRouteFallbackDialogBody", null);
    CARPOOL_DRIVER_ONBOARDING_COMPLETE_BODY = new StringConstant("chauffeurDriverOnboardingCompleteBody", null);
    CARPOOL_DRIVER_ONBOARDING_COMPLETE_TITLE = new StringConstant("chauffeurDriverOnboardingCompleteTitle", null);
    CARPOOL_DRIVER_ONBOARDING_LOCATION_SERVICES_BODY = new StringConstant("chauffeurDriverOnboardingLocationServicesBody", null);
    CARPOOL_DRIVER_ONBOARDING_LOCATION_SERVICES_TITLE = new StringConstant("chauffeurDriverOnboardingLocationServicesTitle", null);
    CARPOOL_DRIVER_ONBOARDING_PROFILE_PHOTO_BODY = new StringConstant("chauffeurDriverOnboardingProfilePhotoBody", null);
    CARPOOL_DRIVER_ONBOARDING_PROFILE_PHOTO_TITLE = new StringConstant("chauffeurDriverOnboardingProfilePhotoTitle", null);
    CC_DIALOG_TITLE = new StringConstant("ccDialogTitle", null);
    CC_DIALOG_SUBTITLE = new StringConstant("ccDialogSubtitle", null);
    INVITE_MENU_TEXT = new StringConstant("inviteMenuItemText", null);
    TWITTER_REFERRAL_BASE_URL = new StringConstant("referralBaseUrlTwitter", "https://lyft.com/i");
    FACEBOOK_REFERRAL_BASE_URL = new StringConstant("referralBaseUrlFacebook", "https://lyft.com/i");
    SMS_REFERRAL_BASE_URL = new StringConstant("referralBaseUrlSms", "https://lyft.com/i");
    CLIPBOARD_REFERRAL_BASE_URL = new StringConstant("referralBaseUrlClipboard", "https://lyft.com/i");
    CLIPBOARD_REFERRAL_BASE_URL_PARALLAX = new StringConstant("referralBaseUrlClipboard2", "https://lyft.com/i");
    EMAIL_REFERRAL_BASE_URL = new StringConstant("referralBaseUrlEmail", "https://lyft.com/i");
    HANGOUTS_REFERRAL_BASE_URL = new StringConstant("referralBaseUrlHangouts", "https://lyft.com/i");
    UNKNOWN_REFERRAL_BASE_URL = new StringConstant("referralBaseUrlUnknown", "https://lyft.com/i");
    CARPOOL_DRIVER_ONBOARDING_PAGE1_TITLE = new StringConstant("chauffeurDriverOnboardingPage1Title", null);
    CARPOOL_DRIVER_ONBOARDING_PAGE1_BODY = new StringConstant("chauffeurDriverOnboardingPage1Body", null);
    CARPOOL_DRIVER_ONBOARDING_PAGE2_TITLE = new StringConstant("chauffeurDriverOnboardingPage2Title", null);
    CARPOOL_DRIVER_ONBOARDING_PAGE2_BODY = new StringConstant("chauffeurDriverOnboardingPage2Body", null);
    CARPOOL_INVITE_TEXT = new StringConstant("chauffeurInviteTextSms", null);
    CARPOOL_INVITE_REFERRAL_BASE_URL = new StringConstant("chauffeurInviteBaseUrl", null);
    WARM_WELCOME_PROFILE_VISIBLE = new BooleanConstant("warmWelcomeProfileImageVisible", Boolean.valueOf(true));
    PG_SOCIAL_PROMPT_FREQUENCY = new LongConstant("pgSocialPromptEveryNRides", Long.valueOf(1L));
    PG_SOCIAL_PROMPT_TOTAL_TIMES = new LongConstant("pgSocialPromptTotalTimes", Long.valueOf(1L));
    ROUTE_DEVIATE_THRESHOLD = new LongConstant("routeDeviateThreshold", Long.valueOf(50L));
    ROUTE_DEVIATE_MAX = new LongConstant("routeDeviateMax", Long.valueOf(2000L));
    DRIVER_PAY_STARTED_MESSAGE = new StringConstant("driverPaymentStartedMessage", null);
    PROMOTE_SPLIT_PAY_HINT = new HashMapConstant("promoteSplitPayHint", HashMap.class, null);
    PROMOTE_GIFTBOX_HINT = new HashMapConstant("promoteGiftBoxHint", HashMap.class, null);
    RIDE_TYPE_HINT = new HashMapConstant("rideTypeHint", HashMap.class, null);
  }
}

/* Location:
 * Qualified Name:     me.lyft.android.application.constants.Constants
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */